package web;

import dao.JdbiFactory;
import dao.JdbiStudentDAO;
import io.jooby.Jooby;
import io.jooby.gson.GsonModule;
import io.jooby.handler.CorsHandler;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;

public class Server extends Jooby {

    public Server() {
        install(new GsonModule());

        // Allow requests from Vue dev server
        use(new CorsHandler());

        Jdbi jdbi = JdbiFactory.create();
        jdbi.installPlugin(new SqlObjectPlugin());

        jdbi.useHandle(handle -> handle.execute(
            "CREATE TABLE IF NOT EXISTS student (" +
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "name VARCHAR(100) NOT NULL, " +
            "major VARCHAR(100) NOT NULL)"
        ));

        JdbiStudentDAO dao = jdbi.onDemand(JdbiStudentDAO.class);

        install(() -> new StudentModule(dao));
    }

    public static void main(String[] args) {
        runApp(args, Server::new);
    }
}