package web;

import dao.JdbiFactory;
import dao.JdbiStudentDAO;
import domain.Student;
import io.jooby.Jooby;
import static io.jooby.Jooby.runApp;
import io.jooby.ServerOptions;
import io.jooby.gson.GsonModule;
import io.jooby.handler.CorsHandler;
import io.jooby.netty.NettyServer;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;

public class Server extends Jooby {

    public Server() {
        install(new GsonModule());

        // Allow requests from Vue dev server
        use(new CorsHandler());

        Jdbi jdbi = JdbiFactory.create();
        jdbi.installPlugin(new SqlObjectPlugin());

        jdbi.useHandle(handle -> handle.execute(
            "CREATE TABLE IF NOT EXISTS student (" +
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "name VARCHAR(100) NOT NULL, " +
            "major VARCHAR(100) NOT NULL)"
        ));

        JdbiStudentDAO dao = jdbi.onDemand(JdbiStudentDAO.class);
        dao.save( new Student(1111, "MikeD", "Swag"));
        dao.save( new Student(1112, "MCA", "Finking"));
        dao.save( new Student(1113, "AdamH", "Brassmonkey"));
        
        install(() -> new StudentModule(dao));
    }

    public static void main(String[] args) {
        System.out.println("bruh");
        ServerOptions options = new ServerOptions().setPort(8085);
        runApp(args, new NettyServer(options), Server::new);
    }
}